package vista;

import controlador.Controlador;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author nahuel
 */
public class VentanConfirmarAsistencia extends javax.swing.JFrame {

    private final Controlador controlador;
    private final JFrame previo;
    private Paciente pa;

    public VentanConfirmarAsistencia(Controlador c, JFrame p) {
        this.controlador = c;
        this.previo = p;
        initComponents();
    }

    public VentanConfirmarAsistencia(Controlador c, JFrame p, Paciente paciente) {
        this.controlador = c;
        this.previo = p;
        this.pa = paciente;
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPacientes = new javax.swing.JList();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaPacientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 510, 180));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnCancelar.setText("Cancelar Asistencia");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 210, 30));

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/confirmar.png"))); // NOI18N
        btnConfirmar.setText("Confirmar Asistencia");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 210, 30));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 210, 30));

        lblp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblp.setForeground(new java.awt.Color(255, 255, 255));
        lblp.setText("Paciente:");
        getContentPane().add(lblp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 510, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Confirmar Asistencia Pacientes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 320, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IM_deteccioaddiccions_nova.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 570, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new VentanaPacientes(controlador, previo).setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Turno turn = (Turno) this.ListaPacientes.getSelectedValue();

        if (!this.ListaPacientes.isSelectionEmpty()) {
            int eleccion = JOptionPane.showConfirmDialog(rootPane, " DESEA CANCELAR ESTE TURNO ", " CANCELAR ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (eleccion == JOptionPane.YES_OPTION) {
                turn.setDisponible(true);
                this.pa.quitarTurnos(turn);
                this.controlador.cancelarTurno(turn);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        Turno turno = (Turno) this.ListaPacientes.getSelectedValue();
        if (!this.ListaPacientes.isSelectionEmpty()) {
            turno.setAsistencia(true);
            this.controlador.editarTurno(turno);
            JOptionPane.showMessageDialog(rootPane, "ASISTENCIA CONFIRMADA", " CONFIRMACION ", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void ListaPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPacientesMouseClicked
        // TODO add your handling code here:
        Turno aux = new Turno();
        Date dia = new Date();
        aux=(Turno)this.ListaPacientes.getSelectedValue();
        if(!this.ListaPacientes.isSelectionEmpty()){
            System.out.println(aux.isAsistencia());
            
            //si el dia de la cita que seleccione es menor
            if(aux.getHoracomienzo().compareTo(dia)> 0){
                //System.out.println("comun");
                //deshabilitarBotonConfirmar();
                habilitarBototnCacelarAsistencia();
            } else {
                //System.out.println("no deberia habilitar los botones");
                if(aux.isAsistencia())
                   deshabilitarBotonConfirmarAsistencia();
                else
                  habilitarBotonConfirmarAsistencia();
                deshabilitarBototnCacelarAsistencia();
            }
        }
    }//GEN-LAST:event_ListaPacientesMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_formWindowGainedFocus

private void limpiar(){
    this.lblp.setText(" Paciente: "+this.pa.getApellidos());
    this.ListaPacientes.setSelectedIndex(-1);
    this.ListaPacientes.setListData(this.controlador.listarTurnos(pa));
}


//METODOS PARA HABILITAR Y DESABILITAR LOS BOTONES
private void habilitarBotonConfirmarAsistencia(){
    this.btnConfirmar.setEnabled(true);
}

private void deshabilitarBotonConfirmarAsistencia(){
    this.btnConfirmar.setEnabled(false);
}

private void habilitarBototnCacelarAsistencia(){
    this.btnCancelar.setEnabled(true);
}

private void deshabilitarBototnCacelarAsistencia(){
    this.btnCancelar.setEnabled(false);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaPacientes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblp;
    // End of variables declaration//GEN-END:variables
}
