package vista;

/**
 *
 * @author Nahu
 */
import modelo.Historiaclinica;
import modelo.Medico;
import modelo.Paciente;
import controlador.Controlador;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nahuel
 */
public class VentanaHistoriales extends javax.swing.JFrame {

    private final Controlador Controlador;
    private final JFrame previo;
    private Historiaclinica h;

    
    public VentanaHistoriales(Controlador c, JFrame p) {
        this.Controlador = c;
        this.previo = p;
        initComponents();
        
        this.setSize(890, 360);

        DefaultComboBoxModel pCombo = new DefaultComboBoxModel(this.Controlador.listarPaciente().toArray());
        this.ComboPacientes.setModel(pCombo);

        DefaultComboBoxModel mCombo1 = new DefaultComboBoxModel(this.Controlador.listarMedico().toArray());
        this.ComboMedicos.setModel(mCombo1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ComboMedicos = new javax.swing.JComboBox<>();
        ComboPacientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnVerListado = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMedicamentos = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(889, 358));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(890, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("HISTORIAS CLINICAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 290, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("F. Historia: dd/MM/yyyy");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 190, 30));
        getContentPane().add(TxtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 140, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Medico");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        getContentPane().add(ComboMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 410, 30));

        getContentPane().add(ComboPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 410, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Paciente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Descripcion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Medicamentos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 160, 30));

        btnVerListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listado.png"))); // NOI18N
        btnVerListado.setText("Ver Listado");
        btnVerListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 160, 30));

        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enter.png"))); // NOI18N
        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 160, 30));

        BtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 160, 30));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 520, -1));

        txtMedicamentos.setColumns(20);
        txtMedicamentos.setRows(5);
        jScrollPane2.setViewportView(txtMedicamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 520, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hiscli.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 110, 80));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bata-de-medico.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 0, 540, 470));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historia_clinica--644x362.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -60, 490, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListadoActionPerformed
        // TODO add your handling code here:
        VentanaListadoHistorias vlh = new VentanaListadoHistorias(Controlador, this);
        this.setVisible(false);
        vlh.setLocationRelativeTo(null);
        vlh.setResizable(false);
        vlh.setVisible(true);

    }//GEN-LAST:event_btnVerListadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        new VentanaRecepcionista(Controlador, previo).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:

        if (this.txtDescripcion.getText().isEmpty() || txtMedicamentos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "INGRESE DESCRIPCION");
        } else {
            Paciente pac = (Paciente) this.ComboPacientes.getSelectedItem();
            Medico med = (Medico) this.ComboMedicos.getSelectedItem();
            this.Controlador.agregarHistoria(pac, this.TxtFecha.getText(),
                    this.txtDescripcion.getText(), this.txtMedicamentos.getText(), med);

            limpiar();
            this.BtnNuevo.setEnabled(true);
            JOptionPane.showMessageDialog(null, "SE CARGO CON EXITO!");

        }

    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void limpiar() {

        this.txtDescripcion.setText("");
        this.txtMedicamentos.setText("");
        bloquear();

    }

    public void bloquear() {
        this.ComboMedicos.setEnabled(false);
        this.ComboMedicos.setEditable(false);
        this.ComboPacientes.setEnabled(false);
        this.ComboPacientes.setEditable(false);
        this.txtDescripcion.setEnabled(false);
        this.txtMedicamentos.setEnabled(false);
        this.BtnGuardar.setEnabled(false);
    }

    public void desbloquear() {
        this.ComboPacientes.setEnabled(true);
        this.ComboMedicos.setEnabled(true);
        this.txtDescripcion.setEnabled(true);
        this.txtMedicamentos.setEnabled(true);
        this.BtnGuardar.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JComboBox<String> ComboMedicos;
    private javax.swing.JComboBox<String> ComboPacientes;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerListado;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtMedicamentos;
    // End of variables declaration//GEN-END:variables
}
