package vista;

import controlador.Controlador;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import modelo.*;

/**
 *
 * @author wagne
 */
public class VentanaPacientes extends javax.swing.JFrame {

    private final Controlador Controlador;
    private final JFrame previo;
    private Paciente pa;

    public VentanaPacientes(Controlador c, JFrame p) {
        this.Controlador = c;
        this.previo = p;
        initComponents();
        //ANCHO, ALTO
        this.setSize(100, 585);
        this.setLocationRelativeTo(null);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PacienteLista = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        VolverVentanaAnterior = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        BotonNuevo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechanacimiento = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        btnTurnosPaciente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setTitle("VentanaPacientes");
        setMinimumSize(new java.awt.Dimension(910, 585));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(910, 585));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PacienteLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PacienteLista.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PacienteLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PacienteListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(PacienteLista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 380, 320));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setText("LISTA DE PACIENTES");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        VolverVentanaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver.png"))); // NOI18N
        VolverVentanaAnterior.setText("Volver");
        VolverVentanaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverVentanaAnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(VolverVentanaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 110, 30));

        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/enter.png"))); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 140, 30));

        BotonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add.png"))); // NOI18N
        BotonNuevo.setText("Nuevo");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("(*)Apellido");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, 30));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("(*)Nombre");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("DATOS PERSONALES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("(*)Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 30));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 170, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("COMPLETE EL SIGUIENTE FORMULARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Id Paciente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("(*)Dni");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("(*)Direccion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 30));

        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 170, 30));

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 170, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("(*)F. Nacimiento dd/MM/yyyy");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        getContentPane().add(labelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 20, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit-user-male.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(70, 70));
        jLabel7.setMinimumSize(new java.awt.Dimension(70, 70));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 150, 150));
        getContentPane().add(txtFechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 170, 30));

        lblId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historia-clinica.jpg"))); // NOI18N
        lblId.setText("labelfondo");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 370));

        btnTurnosPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticket.png"))); // NOI18N
        btnTurnosPaciente.setText("Ver Turnos");
        btnTurnosPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurnosPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnTurnosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 528, 140, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/healthcare-1078x516.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 900, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        if (validarDni() == 0) {
            if (!this.PacienteLista.isSelectionEmpty()) {
                Paciente p = (Paciente) this.PacienteLista.getSelectedValue();
                this.Controlador.editarPaciente(p, this.txtDireccion.getText(), this.txtTelefono.getText());
                JOptionPane.showMessageDialog(null, "EL PACIENTE FUE MODIFICADO CON EXITO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.Controlador.agregarPaciente(this.txtNombre.getText(), this.txtApellido.getText(),
                        this.txtDni.getText(), this.txtDireccion.getText(), this.txtTelefono.getText(),
                        this.txtFechanacimiento.getText());
                JOptionPane.showMessageDialog(null, "EL PACIENTE FUE AGREGADO CON EXITO", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "COMPLETE LOS CAMPOS NECESARIOS", "ERROR", HEIGHT);
        }
        limpiar();//LIMPIO LA VENTANA PACIENTES
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void PacienteListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PacienteListaValueChanged

        //VERIFICAMOS QUE LA LISTA TENGA UN ITEM SELECCIONADO
        if (!this.PacienteLista.isSelectionEmpty()) {
            //obtener la fila seleccionada
            Paciente pacie = (Paciente) this.PacienteLista.getSelectedValue();
            this.pa = (Paciente) this.PacienteLista.getSelectedValue();
            
            //LLEVAMOS LOS ATRIBUTOS A LAS CAJAS DE TEXTO
            this.labelId.setText(String.valueOf(pacie.getIdpac()));
            this.txtApellido.setText(pacie.getApellidos());
            this.txtNombre.setText(pacie.getNombres());
            this.txtDireccion.setText(pacie.getDireccion());
            this.txtDni.setText(pacie.getDni());
            this.txtTelefono.setText(pacie.getTelefono());

            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            String fecha;
            this.txtFechanacimiento.setText(fecha = formatoFecha.format(pacie.getFechanacimiento()));

        }

    }//GEN-LAST:event_PacienteListaValueChanged

    private void VolverVentanaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverVentanaAnteriorActionPerformed

        // TODO add your handling code here:
        //this.setVisible(false);
        new VentanaRecepcionista(Controlador, previo).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverVentanaAnteriorActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnTurnosPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurnosPacienteActionPerformed
        // TODO add your handling code here:
        VentanConfirmarAsistencia vca = new VentanConfirmarAsistencia(this.Controlador, this, this.pa);
        this.setVisible(false);
        vca.setLocationRelativeTo(null);
        vca.setResizable(false);
        vca.setVisible(true);

    }//GEN-LAST:event_btnTurnosPacienteActionPerformed

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void bloquear() {

        this.txtApellido.setEditable(false);
        this.txtNombre.setEditable(false);
        this.txtTelefono.setEditable(false);

    }

    private void limpiar() {
        // limpio las cajas de texto y labels
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtTelefono.setText("");
        this.txtDireccion.setText("");
        this.txtFechanacimiento.setText("");
        this.txtDni.setText("");

        this.labelId.setText("");
        this.PacienteLista.setListData(this.Controlador.listarPaciente().toArray());
        //DESELECCIONO LA LISTA
        this.PacienteLista.clearSelection();

    }

    public int validarDni() {
        try {
            Integer.parseInt(this.txtDni.getText());
            //JOptionPane.showMessageDialog(null, "DATOS VALIDOS");
            this.txtDni.setBorder(BorderFactory.createLineBorder(Color.GREEN, 1));
            return 0; //ok
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "EL DNI DEL PACIENTE DEBE DE SER NUMERICO");
            this.txtDni.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            return 1; //no ok
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JList PacienteLista;
    private javax.swing.JButton VolverVentanaAnterior;
    private javax.swing.JButton btnTurnosPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtFechanacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
